<?php
echo $this->flashMessenger()->render(\Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_ERROR, ['alert', 'alert-danger']);

$title = 'Delete product';
$url   = $this->url('product', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($product->getName()) ?>" <br>
    Description:
    "<?= $this->escapeHtml($product->getDescription()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $product->getId() ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>