<?php
$this->inlineScript()->appendFile('/js/sendemail.js', 'text/javascript');
$title = 'My products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('product', ['action' => 'add']) ?>" class="btn btn-primary">Add new product</a>
</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Created</th>
            <th>Updated</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $product) : ?>
            <tr>
                <td><input type="checkbox" name="send-email" data-id = "<?= $product->id ?>"></td>
                <td><?= $this->escapeHtml($product->name) ?></td>
                <td><?= $this->escapeHtml($product->description) ?></td>
                <td><?= $this->currencyFormat($this->escapeHtml($product->price), 'BRL', null, 'pt_BR'); ?></td>
                <td><?= $this->dateFormat(new DateTime($this->escapeHtml($product->created)), IntlDateFormatter::SHORT, IntlDateFormatter::SHORT, "pt_BR"); ?></td>
                <td><?= $this->dateFormat(new DateTime($this->escapeHtml($product->updated)), IntlDateFormatter::SHORT, IntlDateFormatter::SHORT, "pt_BR"); ?></td>
                <td>
                    <a href="<?= $this->url('product', ['action' => 'edit', 'id' => $product->id]) ?>" class="btn btn-warning">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a href="<?= $this->url('product', ['action' => 'delete', 'id' => $product->id]) ?>" class="btn btn-danger">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>

                </td>
            </tr>
        <?php endforeach; ?>
        <tr><td colspan="7"><button type="button" id="sendemail" class="btn btn-info">Send emails</button></td></tr>
    </tbody>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'product']
) ?>